---

- name: Download and Add APT key
  become: yes
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg

- name: Add apt repository
  become: yes
  apt_repository:
    repo: "deb https://apt.newrelic.com/debian/ newrelic non-free"
    update_cache: yes

- name: Ensure New Relic PHP is installed
  become: yes
  apt:
    pkg: newrelic-php5
    state: present