---

# @docs https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian

- name: Skip install install_newrelic is false
  fail:
    msg: install_newrelic var is set to false
  when: install_newrelic == false
  tags:
    - newrelic

- include: install.yml
  tags:
    - newrelic

- include: configure.yml
  tags:
   - newrelic


