---

# @docs https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian

- include: install.yml
  when: install_newrelic
  tags:
    - newrelic

- include: configure.yml
  when: install_newrelic
  tags:
   - newrelic


